version: "3.8"

services:
  strapi:
    container_name: strapi-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./strapi:/app
    networks:
      - backend
    restart: always

  postgres:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - backend
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - strapi
    networks:
      - backend
    restart: always

networks:
  backend:
