version: "3.8"

services:
  strapi:
    build:
      context: ./strapi     # <-- where your code is
      dockerfile: ../Dockerfile  # <-- Dockerfile is one level above
    container_name: strapi-app
    env_file:
      - ./strapi/.env
    ports:
      - "1337:1337"
    volumes:
      - ./strapi:/app
      - /app/node_modules
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
